action_alias hints kitten hints --alphabet asdfghjklqwertyuiop

# url
map ctrl+shift+p>u hints --type url --program @

# path
map ctrl+shift+p>f hints --type path --program @

# line
map ctrl+shift+p>l hints --type line --program @

# word
map ctrl+shift+p>w hints --type word --program @

# hash
map ctrl+shift+p>h hints --type hash --program @
