## Rosé Pine Moon theme
## by Emilia Dunfelt &lt;edun@dunfelt.se&gt;

[colors]
background=2a273ff2
text=e0def4ff
match=c4a7e7ff
selection=6e6a86ff
selection-text=e0def4ff
selection-match=c4a7e7ff
border=c4a7e7ff
