$display_off = hyprctl dispatch dpms off
$display_on = hyprctl dispatch dpms on

general {
    lock_cmd = pidof hyprlock || hyprlock         # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session      # lock before suspend.
    after_sleep_cmd = $display_on                 # to avoid having to press a key twice to turn on the display.
}

# screen off
listener {
    timeout = 120                                 # 2min
    on-timeout = $display_off                     # screen off when timeout has passed
    on-resume = $display_on                       # screen on when activity is detected after timeout has fired.
}

# lock
listener {
    timeout = 300                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

# suspend
listener {
    timeout = 600                                 # 10min
    on-timeout = systemctl suspend                # suspend pc
}
