#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
BottomUp
RemoveMake
SudoLoop
KeepSrc
CleanAfter
UpgradeMenu

[bin]
GitFlags = -c url."ssh://aur.archlinux.org/".insteadOf=https://aur.archlinux.org/
