#tmux
if command -v tmux &> /dev/null; then
    if [ "$TMUX" = "" ]; then tmux new -A -s shell; fi
fi

# Lines configured by zsh-newuser-install
HISTFILE="$XDG_STATE_HOME/zsh/history"
HISTSIZE=5000
SAVEHIST=5000
setopt autocd extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall and me
mkdir -p ~/.cache/zsh
export ZSH_COMPDUMP=~/.cache/zsh
zstyle :compinstall filename "$ZDOTDIR/.zshrc"
autoload -Uz compinit
compinit
# End of lines added by compinstall


######################
# User configuration #
######################

HYPHEN_INSENSITIVE="true"

setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt hist_ignore_space #ignores commands with a leading space

# Pure theme
fpath+=$ZDOTDIR/themes/pure
autoload promptinit; promptinit
prompt pure


# Disables ugly folder highlighting
export LS_COLORS=$LS_COLORS:'ow=1;34:';

# Add local bin to PATH
export PATH=$PATH:~/.local/bin

# Fix vi mode backspace bug
bindkey "^?" backward-delete-char


################## Plugins ##################
source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZDOTDIR/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Autosuggest settings
bindkey '`' autosuggest-accept
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# History substring search settings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

#############################################

# fzf
if command -v fzf &> /dev/null; then
    if [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]; then
        source /usr/share/doc/fzf/examples/key-bindings.zsh
    else
        source /usr/share/fzf/key-bindings.zsh
    fi
    if [ -f /usr/share/doc/fzf/examples/completion.zsh ]; then
        source /usr/share/doc/fzf/examples/completion.zsh
    else
        source /usr/share/fzf/completion.zsh
    fi

	bindkey '^O' fzf-cd-widget
	bindkey '^K' fzf-file-widget
	export FZF_ALT_C_COMMAND="find . $HOME -type d"
	export FZF_CTRL_T_COMMAND="find . $HOME"

	if command -v fdfind &> /dev/null; then
		export FZF_ALT_C_COMMAND="fdfind . $HOME --type d --hidden"
		export FZF_CTRL_T_COMMAND="fdfind . $HOME --hidden"
	fi

    if command -v fd &> /dev/null; then
        export FZF_ALT_C_COMMAND="fd . $HOME --type d --type l --hidden"
        export FZF_CTRL_T_COMMAND="fd . $HOME --hidden"
    fi

fi

# Extended zshrc
source $ZDOTDIR/extended.zshrc

# Aliases
source $ZDOTDIR/aliases.zsh
source $ZDOTDIR/extended_aliases.zsh
