# tmux
if command -v tmux &> /dev/null; then
    if [ "$TMUX" = "" ]; then tmux new -A -s shell; fi
fi

# zle settings
source $ZDOTDIR/config/zle.zsh

# completion settings
source $ZDOTDIR/config/completion.zsh

# compinit
mkdir -p $XDG_CACHE_HOME/zsh
ZSH_COMPDUMP=$XDG_CACHE_HOME/zsh/zcompdump
autoload -Uz compinit
compinit -d $ZSH_COMPDUMP


###############################
#           Options           #
###############################

setopt auto_cd
setopt extended_glob
setopt hist_ignore_all_dups   # remove older duplicate entries from history
setopt hist_reduce_blanks     # remove superfluous blanks from history items
setopt hist_ignore_space      # ignores commands with a leading space
setopt hist_no_functions      # no function definitions in history
setopt hist_verify            # verify !! expansion
setopt share_history          # share history between shell instances
setopt correct                # spellcheck commands
setopt correct_all            # spellcheck arguments too
setopt menu_complete          # automatically open completion menu on ambiguous completions


###############################
#           Plugins           #
###############################

# Pure theme
fpath+=$ZDOTDIR/themes/pure
autoload promptinit; promptinit
prompt pure
export PURE_PROMPT_SYMBOL=
export PURE_PROMPT_VICMD_SYMBOL=

# Load plugins
source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugins/zsh-bd/bd.zsh
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZDOTDIR/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Autosuggest settings
bindkey '`' autosuggest-accept
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# History substring search settings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# fzf
if command -v fzf &> /dev/null; then
    if [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]; then
        source /usr/share/doc/fzf/examples/key-bindings.zsh
    else
        source /usr/share/fzf/key-bindings.zsh
    fi
    if [ -f /usr/share/doc/fzf/examples/completion.zsh ]; then
        source /usr/share/doc/fzf/examples/completion.zsh
    else
        source /usr/share/fzf/completion.zsh
    fi

    bindkey '^O' fzf-cd-widget
    bindkey '^K' fzf-file-widget
    export FZF_ALT_C_COMMAND="find . $HOME -type d"
    export FZF_CTRL_T_COMMAND="find . $HOME"

    if command -v fdfind &> /dev/null; then
        export FZF_ALT_C_COMMAND="fdfind . $HOME --type d --hidden"
        export FZF_CTRL_T_COMMAND="fdfind . $HOME --hidden"
    fi

    if command -v fd &> /dev/null; then
        export FZF_ALT_C_COMMAND="fd . $HOME --type d --type l --hidden"
        export FZF_CTRL_T_COMMAND="fd . $HOME --hidden"
    fi

fi


###############################
#        Miscellaneous        #
###############################

# PATH
path+=($HOME/.local/bin $CARGO_HOME/bin $XDG_DATA_HOME/npm/bin)
export PATH

# Extended zshrc
source $ZDOTDIR/extended.zshrc

# Aliases
source $ZDOTDIR/config/aliases.zsh
source $ZDOTDIR/extended_aliases.zsh
